---
new_page_extension: md
auto_deploy: false
admin_path: static/cms
webhook_url: 
sections:
- type: directory
  path: src/blog
  label: Stories
  create: documents
  match: "**/*"
  new_doc_ext: md
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: 'uploads/:filename:'
build:
  preview_env:
  - VENDOR_ID=37697
  - VENDOR_AUTH_CODE=749d0cc1a049393168205ca8b693a2f0eb7cb6a1d5905fb4f8
  - GLOBAL_COUPON=""
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
